### ISSUE TITLE
Inaccurate doc comments

### ISSUE THREAD

**Issue by GoodluckH** [Arrow-air/tf-github#79]
Under `/server/src/main.rs`, line 3 has `///module svc_storage generated from svc-storage.proto`. This seems to be specific to the `storage` module. But we should change it to something like `///module svc_template-rust generated from svc-template-rust-grpc.proto` to match with the template.

**Comment by ServiceDog** [comment]
This can actually be fixed in the template repo itself, since main.rs is not provisioned by terraform:

https://github.com/Arrow-air/svc-template-rust/pull/21
